# Generated by Django 4.2.11 on 2025-05-22 20:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('found_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.founditem')),
                ('lost_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.lostitem')),
            ],
        ),
    ]
